/* @jsxImportSource react */

import type { Metadata } from 'next';
import dynamic from 'next/dynamic';

const ReactTooltip = dynamic(() => import('react-tooltip'), { ssr : false });
import { Inter } from 'next/font/google';
import './globals.css';
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>			
			<ReactTooltip
				id='my-tooltip'
				style={{ zIndex: 99 }}
			/>
			<body className={`${inter.className} h-screen font-body`}>{children}</body>
		</html>
	);
}
